INSERT INTO COMPETENCE (INTITULEC, DESCRIPTIONC)
VALUES ('CL', 'Taper sur le clavier');
INSERT INTO MEMBRE (LOGIN, MOTDEPASSE, SURNOM)
VALUES ('riri', 'riri', 'riri');
INSERT INTO MEMBRE (LOGIN, MOTDEPASSE, SURNOM)
VALUES ('fifi', 'fifi', 'fifi');
INSERT INTO PROJET (INTITULE, DESCRIPTION, DIRECTEUR_LOGIN)
VALUES ('Projet', 'PARCKE C EST NOTRE PROJEEEEET !', 'riri');
INSERT INTO PROJET_COMPETENCE
VALUES ('Projet', 'CL');